export default [
  {
    id: 1,
    name: 'FC Barcelona',
    stadium: 'Camp Nou',
    country: 'Spain',
    city: 'Barcelona',
    players: [
      {
        id: 1,
        name: 'Lionel Messi',
        number: 10,
        age: 34,
      },
      {
        id: 2,
        name: 'Antoine Griezmann',
        number: 7,
        age: 30,
      },
      {
        id: 3,
        name: 'Frenkie de Jong',
        number: 21,
        age: 24,
      },
      {
        id: 4,
        name: 'Sergio Busquets',
        number: 5,
        age: 33,
      },
      {
        id: 5,
        name: 'Jordi Alba',
        number: 18,
        age: 32,
      },
      {
        id: 6,
        name: 'Pedri',
        number: 16,
        age: 19,
      },
      {
        id: 7,
        name: 'Ronald Araujo',
        number: 4,
        age: 22,
      },
      {
        id: 8,
        name: 'Gerard Pique',
        number: 3,
        age: 34,
      },
      {
        id: 9,
        name: 'Sergi Roberto',
        number: 20,
        age: 29,
      },
      {
        id: 10,
        name: 'Ousmane Dembele',
        number: 11,
        age: 24,
      },
      {
        id: 11,
        name: 'Marc-Andre ter Stegen',
        number: 1,
        age: 29,
      },
    ],
  },
  {
    id: 2,
    name: 'Real Madrid CF',
    stadium: 'Santiago Bernabeu',
    country: 'Spain',
    city: 'Madrid',
    players: [
      {
        id: 1,
        name: 'Karim Benzema',
        number: 9,
        age: 34,
      },
      {
        id: 2,
        name: 'Eden Hazard',
        number: 7,
        age: 30,
      },
      {
        id: 3,
        name: 'Luka Modric',
        number: 10,
        age: 36,
      },
      {
        id: 4,
        name: 'Toni Kroos',
        number: 8,
        age: 31,
      },
      {
        id: 5,
        name: 'Sergio Ramos',
        number: 4,
        age: 35,
      },
      {
        id: 6,
        name: 'Ferland Mendy',
        number: 23,
        age: 26,
      },
      {
        id: 7,
        name: 'Vinicius Junior',
        number: 20,
        age: 21,
      },
      {
        id: 8,
        name: 'Nacho Fernandez',
        number: 6,
        age: 31,
      },
      {
        id: 9,
        name: 'Lucas Vazquez',
        number: 17,
        age: 30,
      },
      {
        id: 10,
        name: 'Casemiro',
        number: 14,
        age: 29,
      },
      {
        id: 11,
        name: 'Thibaut Courtois',
        number: 1,
        age: 29,
      },
    ],
  },
  {
    id: 3,
    name: 'Manchester United',
    stadium: 'Old Trafford',
    country: 'England',
    city: 'Manchester',
    players: [
      {
        id: 1,
        name: 'David de Gea',
        number: 1,
        age: 30,
      },
      {
        id: 2,
        name: 'Aaron Wan-Bissaka',
        number: 29,
        age: 23,
      },
      {
        id: 3,
        name: 'Harry Maguire',
        number: 5,
        age: 28,
      },
      {
        id: 4,
        name: 'Luke Shaw',
        number: 23,
        age: 26,
      },
      {
        id: 5,
        name: 'Bruno Fernandes',
        number: 18,
        age: 27,
      },
      {
        id: 6,
        name: 'Paul Pogba',
        number: 6,
        age: 28,
      },
      {
        id: 7,
        name: 'Scott McTominay',
        number: 39,
        age: 24,
      },
      {
        id: 8,
        name: 'Marcus Rashford',
        number: 10,
        age: 23,
      },
      {
        id: 9,
        name: 'Edinson Cavani',
        number: 7,
        age: 34,
      },
      {
        id: 10,
        name: 'Mason Greenwood',
        number: 11,
        age: 19,
      },
      {
        id: 11,
        name: 'Jadon Sancho',
        number: 25,
        age: 21,
      },
    ],
  },
  {
    id: 4,
    name: 'Bayern Munich',
    stadium: 'Allianz Arena',
    country: 'Germany',
    city: 'Munich',
    players: [
      {
        id: 1,
        name: 'Manuel Neuer',
        number: 1,
        age: 35,
      },
      {
        id: 2,
        name: 'Benjamin Pavard',
        number: 5,
        age: 25,
      },
      {
        id: 3,
        name: 'Jerome Boateng',
        number: 17,
        age: 32,
      },
      {
        id: 4,
        name: 'Lucas Hernandez',
        number: 21,
        age: 25,
      },
      {
        id: 5,
        name: 'Joshua Kimmich',
        number: 6,
        age: 26,
      },
      {
        id: 6,
        name: 'Leon Goretzka',
        number: 18,
        age: 26,
      },
      {
        id: 7,
        name: 'Kingsley Coman',
        number: 29,
        age: 25,
      },
      {
        id: 8,
        name: 'Serge Gnabry',
        number: 7,
        age: 26,
      },
      {
        id: 9,
        name: 'Thomas Muller',
        number: 25,
        age: 31,
      },
      {
        id: 10,
        name: 'Robert Lewandowski',
        number: 9,
        age: 33,
      },
      {
        id: 11,
        name: 'Leroy Sane',
        number: 10,
        age: 25,
      },
    ],
  },
  {
    id: 5,
    name: 'Liverpool FC',
    stadium: 'Anfield',
    country: 'England',
    city: 'Liverpool',
    players: [
      {
        id: 1,
        name: 'Alisson Becker',
        number: 1,
        age: 29,
      },
      {
        id: 2,
        name: 'Trent Alexander-Arnold',
        number: 66,
        age: 22,
      },
      {
        id: 3,
        name: 'Virgil van Dijk',
        number: 4,
        age: 30,
      },
      {
        id: 4,
        name: 'Joel Matip',
        number: 32,
        age: 29,
      },
      {
        id: 5,
        name: 'Andrew Robertson',
        number: 26,
        age: 27,
      },
      {
        id: 6,
        name: 'Fabinho',
        number: 3,
        age: 27,
      },
      {
        id: 7,
        name: 'Jordan Henderson',
        number: 14,
        age: 31,
      },
      {
        id: 8,
        name: 'Georginio Wijnaldum',
        number: 5,
        age: 30,
      },
      {
        id: 9,
        name: 'Sadio Mane',
        number: 10,
        age: 29,
      },
      {
        id: 10,
        name: 'Roberto Firmino',
        number: 9,
        age: 29,
      },
      {
        id: 11,
        name: 'Mohamed Salah',
        number: 11,
        age: 29,
      },
    ],
  },
  {
    id: 6,
    name: 'Juventus FC',
    stadium: 'Allianz Stadium',
    country: 'Italy',
    city: 'Turin',
    players: [
      {
        id: 1,
        name: 'Wojciech Szczesny',
        number: 1,
        age: 31,
      },
      {
        id: 2,
        name: 'Juan Cuadrado',
        number: 16,
        age: 33,
      },
      {
        id: 3,
        name: 'Matthijs de Ligt',
        number: 4,
        age: 21,
      },
      {
        id: 4,
        name: 'Leonardo Bonucci',
        number: 19,
        age: 34,
      },
      {
        id: 5,
        name: 'Alex Sandro',
        number: 12,
        age: 30,
      },
      {
        id: 6,
        name: 'Weston McKennie',
        number: 14,
        age: 23,
      },
      {
        id: 7,
        name: 'Adrien Rabiot',
        number: 25,
        age: 26,
      },
      {
        id: 8,
        name: 'Federico Chiesa',
        number: 22,
        age: 23,
      },
      {
        id: 9,
        name: 'Paulo Dybala',
        number: 10,
        age: 27,
      },
      {
        id: 10,
        name: 'Dejan Kulusevski',
        number: 44,
        age: 21,
      },
      {
        id: 11,
        name: 'Cristiano Ronaldo',
        number: 7,
        age: 36,
      },
    ],
  },
];
